language: android
jdk: oraclejdk7

android:
  components:
    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew build